# Generated by Django 3.0.5 on 2021-03-22 15:05

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/course-images')),
                ('banner', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/course-banners')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified_chinese', models.CharField(max_length=16)),
                ('traditional_chinese', models.CharField(blank=True, max_length=16)),
                ('pinyin', models.CharField(max_length=64)),
                ('pinnum', models.CharField(blank=True, max_length=64)),
                ('pinplain', models.CharField(blank=True, max_length=64)),
                ('english', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Vocabulary',
                'verbose_name_plural': 'Vocabulary',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('character', models.ManyToManyField(to='core.Vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.SmallIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/stage-images')),
                ('banner', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/stage-banners')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='core.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=256)),
                ('slug', models.SlugField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/level-images')),
                ('banner', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/level-banners')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='core.Stage')),
            ],
        ),
    ]
